# Applications (clients).
#
# Two representative apps:
#   - a Single Page Application (public client, PKCE, no client secret in use)
#   - a Regular Web Application (confidential client, has a client secret)
#
# The regular web app is also given a client grant so it can request tokens for
# the API defined in resource_servers.tf (machine-to-machine style access).

# ---------------------------------------------------------------------------
# Single Page Application (SPA)
# ---------------------------------------------------------------------------

resource "auth0_client" "spa" {
  name        = "${var.environment}-example-spa"
  description = "Example single page application (public client, PKCE)."
  app_type    = "spa"

  callbacks           = var.spa_callback_urls
  allowed_logout_urls = var.spa_logout_urls
  web_origins         = var.spa_web_origins
  allowed_origins     = var.spa_web_origins

  oidc_conformant = true
  grant_types     = ["authorization_code", "refresh_token"]

  jwt_configuration {
    alg = "RS256"
  }

  refresh_token {
    rotation_type                = "rotating"
    expiration_type              = "expiring"
    leeway                       = 0
    token_lifetime               = 2592000 # 30 days
    infinite_token_lifetime      = false
    idle_token_lifetime          = 1296000 # 15 days
    infinite_idle_token_lifetime = false
  }
}

# ---------------------------------------------------------------------------
# Regular Web Application (confidential client)
# ---------------------------------------------------------------------------

resource "auth0_client" "webapp" {
  name        = "${var.environment}-example-webapp"
  description = "Example regular web application (confidential client)."
  app_type    = "regular_web"

  callbacks           = var.webapp_callback_urls
  allowed_logout_urls = var.webapp_logout_urls

  oidc_conformant = true
  grant_types     = ["authorization_code", "refresh_token", "client_credentials"]

  jwt_configuration {
    alg = "RS256"
  }
}

# Client credentials for the confidential app.
# The client secret is available on this resource; it is dynamically generated by
# Auth0. Manage/read it via this resource rather than hard-coding a value.
resource "auth0_client_credentials" "webapp" {
  client_id = auth0_client.webapp.id

  # Confidential clients authenticate to the token endpoint with their secret.
  authentication_method = "client_secret_post"
}

# ---------------------------------------------------------------------------
# Client grant: allow the web app to call the API (client_credentials flow)
# ---------------------------------------------------------------------------

resource "auth0_client_grant" "webapp_to_api" {
  client_id = auth0_client.webapp.id
  audience  = auth0_resource_server.api.identifier

  # Grant only the scopes this app actually needs.
  scopes = ["read:items"]
}
