// @ts-check
// Autogenerated sidebar from the synced docs/ tree (domains -> categories -> diagrams).
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  main: [{ type: 'autogenerated', dirName: '.' }],
};
module.exports = sidebars;
